version: '2'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "13306:3306"
    volumes:
      - "./resources/00-init.sql:/docker-entrypoint-initdb.d/00-init.sql"
      - "./mysqldata:/var/lib/mysql"
        
        #- "/media/langle/2C2C88C82C888F10/mysqldata:/var/lib/mysql"
