version: '2'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=lys091112
    ports:
      - "13306:3306"
    volumes:
      - "./mysql/resources/00-init.sql:/docker-entrypoint-initdb.d/00-init.sql"
    networks:
      - "netName1"


networks:
  netName1:
    driver: bridge
